### PR TITLE
Cody lee solution

### PR DESCRIPTION
**Pull request by codylee02**

### CODE REVIEW

**Comment by jontlancaster** [comment]
Cody, can you tell me who instructed you to complete this project?  I created this as a coding exercise for an open position on my team, but I wasn't expecting anything right now.  Just curious if someone else I work with is using it as well or if you did it for some other reason.  Thanks.

**Comment by codylee02** [comment]
Hi Jon,
I was instructed to complete it as a challenge for an open position on Scott McKenrick's team. I noticed that your git username looked a bit different than what I would expect for Scott, so I closed the PR

**Comment by jontlancaster** [comment]
OK.  He does work with me, but on another team, I will let him know you submitted this in case he's not aware.  Thanks for getting back to me.

**Comment by codylee02** [comment]
Oh thanks Jon, sounds good

**Pull request closed without merging**
